language: node_js
node_js: 
    - "12.16.2"
dist: trusty
services:
    - mongodb
env: 
    - NODE_ENV=ci PORT=3001
cache:
    directories:
        - node_modules
install:
    - npm install
script:
    - npm run test